name = "boyibo"
compatibility_date = "2024-01-01"

[env.production]
# Cloudflare Pages配置
pages_build_output_dir = "dist"

# R2存储绑定
[[env.production.r2_buckets]]
binding = "BOYIBO_STORAGE"
bucket_name = "boyibo-storage"

# 环境变量
[env.production.vars]
ENVIRONMENT = "production"
R2_ACCOUNT_ID = "9d12d28ae909512f60a7ad1545c2dacd"
R2_BUCKET_NAME = "boyibo-storage"

# 开发环境配置
[env.development]
pages_build_output_dir = "dist"

[[env.development.r2_buckets]]
binding = "BOYIBO_STORAGE"
bucket_name = "boyibo-storage"

[env.development.vars]
ENVIRONMENT = "development"
R2_ACCOUNT_ID = "9d12d28ae909512f60a7ad1545c2dacd"
R2_BUCKET_NAME = "boyibo-storage"